import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:wp_commander/domain/usecases/sites/add_site_usecase.dart';

import '../../domain/entities/site_entity.dart';
import '../notifiers/sites_notifier.dart';

class AddSiteDialog extends ConsumerWidget {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _urlController = TextEditingController();
  final _apiKeyController = TextEditingController();

  AddSiteDialog({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return AlertDialog(
      title: const Text('Add Site'),
      content: Form(
        key: _formKey,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextFormField(
              controller: _nameController,
              decoration: const InputDecoration(labelText: 'Name'),
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return 'Please enter a name';
                }
                return null;
              },
            ),
            TextFormField(
              controller: _urlController,
              decoration: const InputDecoration(labelText: 'URL'),
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return 'Please enter a URL';
                }
                return null;
              },
            ),
            TextFormField(
              controller: _apiKeyController,
              decoration: const InputDecoration(labelText: 'API Key'),
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return 'Please enter an API Key';
                }
                return null;
              },
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () {
            Navigator.of(context).pop();
          },
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: () {
            if (_formKey.currentState!.validate()) {
              final site = SiteEntity(
                id: '', // The ID will be generated by the server
                name: _nameController.text,
                url: _urlController.text,
                apiKey: _apiKeyController.text,
                createdAt: DateTime.now(),
              );
              ref.read(sitesNotifierProvider.notifier).addSite(AddSiteParams(site: site, name: '', url: '', apiKey: ''));
              Navigator.of(context).pop();
            }
          },
          child: const Text('Add'),
        ),
      ],
    );
  }
}
