// Mocks generated by Mockito 5.4.4 from annotations
// in wp_commander/test/data/repositories/site_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wp_commander/data/datasources/local/site_local_datasource.dart'
    as _i3;
import 'package:wp_commander/data/models/site_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSiteModel_0 extends _i1.SmartFake implements _i2.SiteModel {
  _FakeSiteModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SiteLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSiteLocalDataSource extends _i1.Mock
    implements _i3.SiteLocalDataSource {
  MockSiteLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.SiteModel>> getSites() => (super.noSuchMethod(
        Invocation.method(
          #getSites,
          [],
        ),
        returnValue: _i4.Future<List<_i2.SiteModel>>.value(<_i2.SiteModel>[]),
      ) as _i4.Future<List<_i2.SiteModel>>);

  @override
  _i4.Future<void> cacheSites(List<_i2.SiteModel>? sites) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheSites,
          [sites],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSite,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SiteModel?> getSiteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getSiteById,
          [id],
        ),
        returnValue: _i4.Future<_i2.SiteModel?>.value(),
      ) as _i4.Future<_i2.SiteModel?>);

  @override
  _i4.Future<_i2.SiteModel> addSite(_i2.SiteModel? site) => (super.noSuchMethod(
        Invocation.method(
          #addSite,
          [site],
        ),
        returnValue: _i4.Future<_i2.SiteModel>.value(_FakeSiteModel_0(
          this,
          Invocation.method(
            #addSite,
            [site],
          ),
        )),
      ) as _i4.Future<_i2.SiteModel>);

  @override
  _i4.Future<void> updateSite(_i2.SiteModel? site) => (super.noSuchMethod(
        Invocation.method(
          #updateSite,
          [site],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
