// Mocks generated by Mockito 5.4.4 from annotations
// in wp_commander/test/domain/usecases/add_site_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wp_commander/domain/entities/site_entity.dart' as _i2;
import 'package:wp_commander/domain/repositories/site_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSiteEntity_0 extends _i1.SmartFake implements _i2.SiteEntity {
  _FakeSiteEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SiteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSiteRepository extends _i1.Mock implements _i3.SiteRepository {
  MockSiteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.SiteEntity>> getSites() => (super.noSuchMethod(
        Invocation.method(
          #getSites,
          [],
        ),
        returnValue: _i4.Future<List<_i2.SiteEntity>>.value(<_i2.SiteEntity>[]),
      ) as _i4.Future<List<_i2.SiteEntity>>);

  @override
  _i4.Future<_i2.SiteEntity> addSite(_i2.SiteEntity? site) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSite,
          [site],
        ),
        returnValue: _i4.Future<_i2.SiteEntity>.value(_FakeSiteEntity_0(
          this,
          Invocation.method(
            #addSite,
            [site],
          ),
        )),
      ) as _i4.Future<_i2.SiteEntity>);

  @override
  _i4.Future<void> deleteSite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSite,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
